#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Atlas Reactorum — metadata/build_inventory.sh
# Generated bytecode, local virtual environments and tool caches are not
# repository content. Counting them would overstate the inventory, which is
# published as a measure of what the library actually holds.
PRUNE=( -path "*/__pycache__/*" -o -path "*/.venv/*" -o -path "*/.git/*" -o -path "*/.mypy_cache/*" -o -path "*/.ruff_cache/*" -o -path "*/.pytest_cache/*" -o -path "*/.pytest-scratch/*" -o -path "*/docs/internal/*" -o -name '.coverage*' )

set -euo pipefail

if [[ -v SOURCE_DATE_EPOCH ]]; then
  [[ "$SOURCE_DATE_EPOCH" =~ ^[0-9]+$ ]] || { printf 'SOURCE_DATE_EPOCH must be nonnegative epoch seconds.\n' >&2; exit 1; }
  generated_utc="$(date -u -d "@$SOURCE_DATE_EPOCH" '+%Y-%m-%dT%H:%M:%SZ')"
else
  generated_utc="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
fi

library_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
metadata_dir="$library_root/metadata"
merged="$metadata_dir/all_sources.tsv"
inventory="$metadata_dir/library_inventory.tsv"
validation="$metadata_dir/validation_report.txt"
duplicates="$metadata_dir/duplicate_files.tsv"

catalogs=(
  "$library_root/01_nuclear/sources.tsv"
  "$library_root/02_chemical_biochemical/sources.tsv"
  "$library_root/03_hybrid_emerging/sources.tsv"
)

expected_header=$'section\tcategory\ttitle\tyear\tauthors_or_org\turl\tlocal_file\taccess\tstatus\tnotes'
printf '%s\n' "$expected_header" > "$merged"

for catalog in "${catalogs[@]}"; do
  [[ -f "$catalog" ]] || continue
  section="$(basename "$(dirname "$catalog")")"
  awk -v section="$section" 'BEGIN { FS=OFS="\t" } NR > 1 { print section, $0 }' "$catalog" >> "$merged"
done

printf 'section\tfiles\tbytes\tpdf\tzip\thtml\tother\n' > "$inventory"
for section_path in "$library_root"/01_nuclear "$library_root"/02_chemical_biochemical "$library_root"/03_hybrid_emerging "$library_root"/04_interactive_presentation "$library_root"/05_global_reactor_map; do
  [[ -d "$section_path" ]] || continue
  section="$(basename "$section_path")"
  files="$(find "$section_path" -type f ! -name 'SHA256SUMS' ! \( "${PRUNE[@]}" \) | wc -l)"
  bytes="$(find "$section_path" -type f ! -name 'SHA256SUMS' ! \( "${PRUNE[@]}" \) -printf '%s\n' | awk '{ total += $1 } END { print total + 0 }')"
  pdf="$(find "$section_path" -type f ! \( "${PRUNE[@]}" \) -iname '*.pdf' | wc -l)"
  zip="$(find "$section_path" -type f ! \( "${PRUNE[@]}" \) -iname '*.zip' | wc -l)"
  html="$(find "$section_path" -type f ! \( "${PRUNE[@]}" \) \( -iname '*.html' -o -iname '*.htm' \) | wc -l)"
  other=$((files - pdf - zip - html))
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$section" "$files" "$bytes" "$pdf" "$zip" "$html" "$other" >> "$inventory"
done

{
  printf 'Reactor Research Library validation\n'
  printf 'Generated (UTC): %s\n' "$generated_utc"
  printf 'Catalog entries: %s\n' "$(( $(wc -l < "$merged") - 1 ))"
  printf 'Repository PDFs: %s\n' "$(find "$library_root" -type f ! \( "${PRUNE[@]}" \) -iname '*.pdf' | wc -l)"
  printf 'Repository ZIPs: %s\n' "$(find "$library_root" -type f ! \( "${PRUNE[@]}" \) -iname '*.zip' | wc -l)"
  printf '\nPDF validation failures:\n'
  pdf_failures=0
  while IFS= read -r -d '' pdf_file; do
    if ! head -c 5 "$pdf_file" | grep -q '^%PDF-'; then
      printf '%s\n' "${pdf_file#"$library_root"/}"
      pdf_failures=$((pdf_failures + 1))
    fi
  done < <(find "$library_root" -type f ! \( "${PRUNE[@]}" \) -iname '*.pdf' -print0 | LC_ALL=C sort -z)
  [[ "$pdf_failures" -gt 0 ]] || printf 'none\n'

  printf '\nZIP validation failures:\n'
  zip_failures=0
  while IFS= read -r -d '' zip_file; do
    if ! unzip -tqq "$zip_file" >/dev/null 2>&1; then
      printf '%s\n' "${zip_file#"$library_root"/}"
      zip_failures=$((zip_failures + 1))
    fi
  done < <(find "$library_root" -type f ! \( "${PRUNE[@]}" \) -iname '*.zip' -print0 | LC_ALL=C sort -z)
  [[ "$zip_failures" -gt 0 ]] || printf 'none\n'

  printf '\nEmpty files:\n'
  empty_count=0
  while IFS= read -r -d '' empty_file; do
    printf '%s\n' "${empty_file#"$library_root"/}"
    empty_count=$((empty_count + 1))
  done < <(find "$library_root" -type f ! \( "${PRUNE[@]}" \) -empty -print0 | LC_ALL=C sort -z)
  [[ "$empty_count" -gt 0 ]] || printf 'none\n'

  printf '\nMissing catalog local_file references:\n'
  missing_refs=0
  for catalog in "${catalogs[@]}"; do
    [[ -f "$catalog" ]] || continue
    section_path="$(dirname "$catalog")"
    while IFS= read -r local_file; do
      if [[ ! -e "$section_path/$local_file" ]]; then
        printf '%s: %s\n' "${catalog#"$library_root"/}" "$local_file"
        missing_refs=$((missing_refs + 1))
      fi
    done < <(awk -F '\t' 'NR > 1 && $6 != "" { print $6 }' "$catalog")
  done
  [[ "$missing_refs" -gt 0 ]] || printf 'none\n'
} > "$validation"

hash_tmp="$(mktemp)"
trap 'rm -f "$hash_tmp"' EXIT
(
cd "$library_root"
find . -type f \
  ! -name 'SHA256SUMS' \
  ! \( "${PRUNE[@]}" \) \
  ! -path './metadata/duplicate_files.tsv' \
  ! -path './metadata/validation_report.txt' \
  -print0 | sort -z | xargs -0 sha256sum > "$hash_tmp"
)

printf 'sha256\tcopies\tpaths\n' > "$duplicates"
awk 'BEGIN { OFS="\t" } { hash=$1; path=substr($0, length(hash) + 3); count[hash]++; paths[hash]=paths[hash] (paths[hash] ? " | " : "") path } END { for (h in count) if (count[h] > 1) print h, count[h], paths[h] }' "$hash_tmp" | sort >> "$duplicates"

for section_path in "$library_root"/01_nuclear "$library_root"/02_chemical_biochemical "$library_root"/03_hybrid_emerging; do
  (
    cd "$section_path"
    find . -type f ! -name 'SHA256SUMS' ! \( "${PRUNE[@]}" \) -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS
  )
done

(
  cd "$library_root"
  checksum_paths=(00_index 01_nuclear 02_chemical_biochemical 03_hybrid_emerging metadata)
  [[ -d 04_interactive_presentation ]] && checksum_paths+=(04_interactive_presentation)
  [[ -d 05_global_reactor_map ]] && checksum_paths+=(05_global_reactor_map)
  find "${checksum_paths[@]}" \
    -type f ! -name 'SHA256SUMS' ! \( "${PRUNE[@]}" \) ! -path 'metadata/validation_report.txt' \
    -print0 | sort -z | xargs -0 sha256sum > metadata/SHA256SUMS
)

printf 'Created %s, %s, %s and checksums.\n' "$merged" "$inventory" "$validation"
