# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Atlas Reactorum — Makefile

PYTHON ?= python3.12
VENV   ?= .venv
ATLAS_PYTHON ?= $(abspath $(VENV))/bin/python
SHELL  := /bin/bash

.DEFAULT_GOAL := help
.PHONY: help setup hooks lint native-test-docs native-shell native-javascript native-js-lint native-js-types native-js-format native-map-runtime native-web native-html native-css native-web-format dependency-audit typecheck test validate build verify preflight clean research-example

help:  ## List the available targets
	@grep -hE '^[a-z-]+:.*##' $(MAKEFILE_LIST) | sed 's/:.*##/\t/' | sort

setup:  ## Create the development environment from the verified lock
	$(PYTHON) -m venv $(VENV)
	$(VENV)/bin/python -m pip install --require-hashes --no-deps -r requirements-dev.txt
	npm ci

hooks:  ## Check staged source hooks using the same development graph
	ATLAS_PYTHON="$(ATLAS_PYTHON)" PATH="$(abspath $(VENV))/bin:$$PATH" $(VENV)/bin/python -m pre_commit run --all-files --show-diff-on-failure

lint: native-languages native-ffi native-test-docs native-shell native-js-lint native-js-format native-web native-notebooks  ## Lint and check formatting
	$(VENV)/bin/python -m ruff check .
	$(VENV)/bin/python -m ruff format --check .

native-test-docs:  ## Require native contracts throughout the maintained test tree
	$(VENV)/bin/python -m ruff check --select D --config 'lint.per-file-ignores = {}' tests

.PHONY: native-languages
native-languages:  ## Refuse unqualified source languages and compiled backend artifacts
	node tools/languages.cjs

.PHONY: native-python-stubs
native-python-stubs: native-languages  ## Bind generated declarations to actual Python source and runtime
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node tools/stubs.cjs

.PHONY: native-ffi
native-ffi: native-languages  ## Bind native FFI imports to qualified complete runtime source
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node tools/ffi.cjs

native-shell:  ## ShellCheck and shfmt on tracked and new shell source
	@set -euo pipefail; \
	  for tool in git shellcheck shfmt; do command -v "$$tool" >/dev/null; done; \
	  shellcheck --version | grep -qx 'version: 0.9.0'; \
	  test "$$(shfmt --version)" = '3.8.0'; \
	  files="$$(mktemp)"; trap 'rm -f "$$files"' EXIT; \
	  git ls-files --cached --others --exclude-standard --deduplicate -z -- '*.sh' >"$$files"; \
	  test -s "$$files"; \
	  while IFS= read -r -d '' file; do if [[ ! -f "$$file" || ! -r "$$file" || -L "$$file" ]]; then printf 'native source unavailable or symlink: %s\n' "$$file" >&2; exit 1; fi; done <"$$files"; \
	  xargs -0 -r shellcheck --severity=style <"$$files"; \
	  xargs -0 -r shfmt -d -i 4 -ci <"$$files"

native-javascript: native-languages  ## Node syntax checks on tracked and new JS, CJS and MJS source
	@set -euo pipefail; \
	  for tool in git node; do command -v "$$tool" >/dev/null; done; \
	  test "$$(node --version)" = 'v24.21.0'; \
	  files="$$(mktemp)"; trap 'rm -f "$$files"' EXIT; \
	  git ls-files --cached --others --exclude-standard --deduplicate -z -- '*.js' '*.cjs' '*.mjs' >"$$files"; \
	  test -s "$$files"; \
	  while IFS= read -r -d '' file; do \
	    if [[ ! -f "$$file" || ! -r "$$file" || -L "$$file" ]]; then printf 'native source unavailable or symlink: %s\n' "$$file" >&2; exit 1; fi; \
	    node --check "$$file"; \
	  done <"$$files"

native-js-lint: native-javascript  ## Native ESLint and JSDoc across tracked and new JavaScript
	node tools/javascript.cjs lint

native-js-types: native-javascript  ## Strict TypeScript on handwritten JavaScript and fixtures
	node tools/javascript.cjs types

native-js-format: native-javascript  ## Native formatting with source-bound generated bytes preserved
	node tools/javascript.cjs format

native-map-runtime:  ## Source-bound native Node/Cairo and Chrome qualification of every map module
	$(VENV)/bin/python -m pytest tests/test_map_runtime_browser.py

native-web: native-languages native-html native-css native-web-format  ## Native HTML/CSS source semantics and formatting

native-html:  ## Complete maintained and new HTML source through HTML-validate
	node tools/web.cjs html

native-css:  ## Native CSS grammar and all resolved variable alternatives
	node tools/web.cjs css

native-web-format:  ## Locked Prettier on complete maintained and new HTML/CSS
	node tools/web.cjs format

.PHONY: native-notebooks native-notebook-runtime
native-notebooks: native-languages  ## Native notebook schema, Python lint/format and strict cell types
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node tools/notebooks.cjs static

native-notebook-runtime:  ## Execute every unchanged notebook cell in its locked isolated Jupyter kernel
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node tools/notebooks.cjs execute

dependency-audit:  ## Blocking advisory checks against both complete dependency locks
	$(VENV)/bin/python -m pip_audit --require-hashes -r requirements-dev.txt
	npm audit --include=dev

typecheck: native-languages native-js-types native-notebooks native-python-stubs  ## Strict mypy across every source directory
	ATLAS_MYPY="$(abspath $(VENV))/bin/mypy" ./tools/typecheck.sh

test:  ## Python tests at the 100 per cent coverage floor
	@mapfile -t source_dirs < <(find . -name '*.py' \
	  -not -path './tests/*' -not -path '*/.venv/*' \
	  -not -path '*/node_modules/*' -not -path '*/.git/*' \
	  -not -path '*/__pycache__/*' -not -path '*/.mypy_cache/*' \
	  -not -path '*/.pytest-scratch/*' -not -path '*/docs/internal/*' \
	  -printf '%h\n' | sort -u); \
	  test "$${#source_dirs[@]}" -gt 0 || exit 1; \
	  coverage_args=(); \
	  for directory in "$${source_dirs[@]}"; do coverage_args+=("--cov=$$directory"); done; \
	  ATLAS_PYTHON="$(ATLAS_PYTHON)" $(VENV)/bin/python -m pytest tests/ "$${coverage_args[@]}"

validate: native-javascript native-web native-notebook-runtime  ## Presentation checks, including the map engine tests
	PATH="$(abspath $(VENV))/bin:$$PATH" bash 04_interactive_presentation/validate.sh

build:  ## Verify pinned FFDB and regenerate offline exports and inventory
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node 04_interactive_presentation/scripts/export_taxonomy.cjs
	ATLAS_PYTHON="$(ATLAS_PYTHON)" node 04_interactive_presentation/scripts/evidence_history.cjs --build .
	$(VENV)/bin/python 04_interactive_presentation/scripts/build_datasets.py
	$(VENV)/bin/python metadata/map_basemap/build.py
	$(VENV)/bin/python metadata/coverage_audit/build_coverage.py
	./metadata/build_inventory.sh

preflight:  ## Reproducibility, docs, secrets and header checks
	$(VENV)/bin/python tools/preflight.py

verify: lint typecheck test validate preflight  ## Everything a change must pass

clean:  ## Remove local caches and scratch space
	rm -rf .mypy_cache .ruff_cache .pytest_cache .pytest-scratch .coverage

research-example:  ## Restore the included comparison without changing source files
	$(VENV)/bin/python -c 'import json; from pathlib import Path; from tools.research_comparison import restore_comparison; p=Path("examples/research"); m=json.loads((p/"comparison-manifest.json").read_text()); print(json.dumps(restore_comparison(Path.cwd(),p/m["comparison_file"],m["profile_sha256"],m["bundle_sha256"]),ensure_ascii=False,indent=2,allow_nan=False))'
